// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelationshipService.Data;

#nullable disable

namespace RelationshipService.Migrations
{
    [DbContext(typeof(RelationshipDbContext))]
    partial class RelationshipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RelationshipService.Entities.PaymentOrderRelation", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountAllocated")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PaymentId", "OrderId");

                    b.ToTable("PaymentOrderRelations");
                });

            modelBuilder.Entity("RelationshipService.Entities.UserStoreRelation", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId", "StoreId");

                    b.ToTable("UserStoreRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
