// <auto-generated />
using System;
using BusinessService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessService.Migrations
{
    [DbContext(typeof(BusinessDbContext))]
    [Migration("20251020024225_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessService.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThemeColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("BusinessService.Entities.StoreCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StoreCategories");
                });

            modelBuilder.Entity("BusinessService.Entities.StoreCategoryRelation", b =>
                {
                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StoreCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StoreId", "StoreCategoryId");

                    b.HasIndex("StoreCategoryId");

                    b.ToTable("StoreCategoryRelations");
                });

            modelBuilder.Entity("BusinessService.Entities.StoreTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StoreTags");
                });

            modelBuilder.Entity("BusinessService.Entities.StoreTagRelation", b =>
                {
                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StoreTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StoreId", "StoreTagId");

                    b.HasIndex("StoreTagId");

                    b.ToTable("StoreTagRelations");
                });

            modelBuilder.Entity("BusinessService.Entities.StoreCategoryRelation", b =>
                {
                    b.HasOne("BusinessService.Entities.StoreCategory", "StoreCategory")
                        .WithMany("StoreCategoryRelations")
                        .HasForeignKey("StoreCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessService.Entities.Store", "Store")
                        .WithMany("StoreCategoryRelations")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("StoreCategory");
                });

            modelBuilder.Entity("BusinessService.Entities.StoreTagRelation", b =>
                {
                    b.HasOne("BusinessService.Entities.Store", "Store")
                        .WithMany("StoreTagRelations")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessService.Entities.StoreTag", "StoreTag")
                        .WithMany("StoreTagRelations")
                        .HasForeignKey("StoreTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("StoreTag");
                });

            modelBuilder.Entity("BusinessService.Entities.Store", b =>
                {
                    b.Navigation("StoreCategoryRelations");

                    b.Navigation("StoreTagRelations");
                });

            modelBuilder.Entity("BusinessService.Entities.StoreCategory", b =>
                {
                    b.Navigation("StoreCategoryRelations");
                });

            modelBuilder.Entity("BusinessService.Entities.StoreTag", b =>
                {
                    b.Navigation("StoreTagRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
